[package]
name = "rpeg"
version = "0.1.0"
edition = "2021"

[dependencies]
array2 = { path = "../array2" }
bitpack = { path = "../bitpack" }
clap = { version = "4.5.32", features = ["derive"] }
csc411_arith = "0.1.0"

csc411_image = "0.5.2"
csc411_rpegio = "0.4.0"
rand = "0.9.0"
